export const pathSegmentLabels: Record<string, string> = {
  dashboard: "Dashboard",
  usuarios: "Usuarios",
  clases: "Clases",
  reservas: "Reservas",
  pagos: "Pagos",
  planes: "Planes",
  coaches: "Coaches",
  attendance: "Asistencia",
  schedule: "Horario",
  reportes: "Reportes",
  politica: "Política del Estudio",
  configuracion: "Configuración",
  calendario: "Calendario",
  historico: "Histórico",
}
